
#ifndef ZSVersion_h
#define ZSVersion_h

#define ZS_VERSION_MAJOR 1
#define ZS_VERSION_MINOR 2
#define ZS_VERSION_PATCH 1

#define ZS_VERSION_STRINGIFY_IMPL(x) #x
#define ZS_VERSION_STRINGIFY(x) ZS_VERSION_STRINGIFY_IMPL(x)

#define ZS_VERSION_STRING \
    ZS_VERSION_STRINGIFY(ZS_VERSION_MAJOR) "." \
    ZS_VERSION_STRINGIFY(ZS_VERSION_MINOR) "." \
    ZS_VERSION_STRINGIFY(ZS_VERSION_PATCH)

#endif
